//! Backend / packaging (UBT Phase 4, milestone M1): turn the transpiled C plus
//! the HLE compatibility layer into a *native, runnable* executable for the
//! target OS.
//!
//! M1 scope: a freestanding Win32 PE (kernel32 imports only) is transpiled to C
//! by the ARET middle-end, its API imports are intercepted into HLE shim calls
//! (see `ir::build::name_calls_in_expr`), and this builder links the result with
//! `runtime/aret_hle` and a generated `main` into a native ELF via the system C
//! compiler. The produced binary runs natively — not under an emulator or Wine.

use crate::analysis::Function;
use crate::emit;
use crate::ir;
use crate::loader::Program;
use crate::opt;
use crate::ssa;
use anyhow::{bail, Context, Result};
use std::path::Path;
use std::process::Command;

/// The HLE runtime, embedded so the built `aret` binary is self-contained.
const HLE_H: &str = include_str!("../../runtime/aret_hle/aret_hle.h");
const HLE_C: &str = include_str!("../../runtime/aret_hle/aret_hle.c");

pub struct TranspileReport {
    pub out_dir: std::path::PathBuf,
    pub binary: std::path::PathBuf,
    pub functions: usize,
    pub bits: u32,
    /// Captured stdout if the binary was run, else `None`.
    pub run_output: Option<String>,
}

impl TranspileReport {
    pub fn render(&self) -> String {
        let mut s = String::new();
        s.push_str("ARET transpile (UBT M1) — native recompile\n");
        s.push_str(&format!("  functions:  {}\n", self.functions));
        s.push_str(&format!("  bitness:    {}-bit\n", self.bits));
        s.push_str(&format!("  output dir: {}\n", self.out_dir.display()));
        s.push_str(&format!("  binary:     {}\n", self.binary.display()));
        if let Some(out) = &self.run_output {
            s.push_str("  --- program output ---\n");
            for line in out.lines() {
                s.push_str("  | ");
                s.push_str(line);
                s.push('\n');
            }
        }
        s
    }
}

/// Memory Layout Mapper (UBT Phase 3, design doc §2): some binaries reference
/// data by its original absolute virtual address (a global string in `.rdata`,
/// a table in `.data`). The transpiled C keeps those as raw addresses, so the
/// recompiled process must place the original section bytes back at those VAs.
///
/// This emits an `aret_layout.c` whose `__aret_map_memory()` `mmap(MAP_FIXED)`s
/// the span covering every non-executable data section and copies the original
/// bytes in. Called once before the entry point. (The binary is linked `-no-pie`
/// so its own segments sit elsewhere and the original low VAs stay free.)
fn emit_layout(prog: &Program) -> Option<String> {
    use std::fmt::Write as _;

    // Data sections to restore: non-executable, addressed, with content. The
    // import (IAT) and reloc sections are harmless to map but unnecessary —
    // their VAs are never dereferenced (calls are intercepted), yet keeping the
    // filter simple (all non-exec data) costs little and is robust.
    let secs: Vec<&crate::loader::Section> = prog
        .sections
        .iter()
        .filter(|s| !s.executable && s.address != 0 && !s.data.is_empty())
        .collect();
    if secs.is_empty() {
        return None;
    }

    let mut s = String::new();
    s.push_str(
        "/* Generated by ARET — Memory Layout Mapper. Restores the original data\n   sections at their virtual addresses so absolute pointers resolve. */\n",
    );
    s.push_str("#include <stdint.h>\n#include <string.h>\n#include <stdio.h>\n#include <stdlib.h>\n#include <sys/mman.h>\n\n");

    for (i, sec) in secs.iter().enumerate() {
        let _ = writeln!(
            s,
            "/* {} @ 0x{:x} ({} bytes) */",
            sec.name,
            sec.address,
            sec.data.len()
        );
        let _ = write!(s, "static const unsigned char S{i}[] = {{");
        for (j, b) in sec.data.iter().enumerate() {
            if j % 16 == 0 {
                s.push_str("\n    ");
            }
            let _ = write!(s, "0x{:02x},", b);
        }
        s.push_str("\n};\n");
    }

    s.push_str("\nstruct aret_sec { uint32_t va; uint32_t len; const unsigned char *data; };\n");
    s.push_str("static const struct aret_sec aret_secs[] = {\n");
    for (i, sec) in secs.iter().enumerate() {
        let _ = writeln!(
            s,
            "    {{ 0x{:x}u, {}u, S{i} }},",
            sec.address,
            sec.data.len()
        );
    }
    s.push_str("};\n\n");

    s.push_str(
        "void __aret_map_memory(void) {\n\
\x20   const uint32_t PAGE = 0x1000u;\n\
\x20   uint64_t lo = 0xffffffffull, hi = 0;\n\
\x20   unsigned i;\n\
\x20   for (i = 0; i < sizeof(aret_secs)/sizeof(aret_secs[0]); i++) {\n\
\x20       uint64_t a = aret_secs[i].va & ~(uint64_t)(PAGE - 1);\n\
\x20       uint64_t e = (aret_secs[i].va + aret_secs[i].len + PAGE - 1) & ~(uint64_t)(PAGE - 1);\n\
\x20       if (a < lo) lo = a;\n\
\x20       if (e > hi) hi = e;\n\
\x20   }\n\
\x20   void *p = mmap((void *)(uintptr_t)lo, (size_t)(hi - lo),\n\
\x20                  PROT_READ | PROT_WRITE,\n\
\x20                  MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, -1, 0);\n\
\x20   if (p == MAP_FAILED) { perror(\"aret: mmap layout\"); exit(70); }\n\
\x20   for (i = 0; i < sizeof(aret_secs)/sizeof(aret_secs[0]); i++)\n\
\x20       memcpy((void *)(uintptr_t)aret_secs[i].va, aret_secs[i].data, aret_secs[i].len);\n\
}\n",
    );
    Some(s)
}

/// Build IR for one recovered function and lower it for shared-stack transpilation
/// (UBT M3). Unlike the verify/decompile chain, this does *not* promote stack
/// slots to private per-function locals: every stack access stays raw memory into
/// one global stack, and `__esp` is threaded through calls so stack-passed
/// arguments cross functions.
fn lower(prog: &Program, f: &Function) -> ir::types::IrFunction {
    // Force raw frame memory so `[ebp+d]` stays a load from the shared stack
    // (build_ir ORs this in, then resets it afterwards).
    ir::lift::set_frames_off(true);
    let mut irf = ir::build::build_ir(prog, f);
    ir::build::thread_internal_call_esp(&mut irf);
    ssa::to_ssa(&mut irf);
    opt::optimize(&mut irf);
    irf
}

/// Transpile `funcs` to C, link with the HLE runtime, and produce a native
/// executable in `out_dir`. When `run` is set, execute it and capture stdout.
pub fn transpile(
    prog: &Program,
    funcs: &[&Function],
    out_dir: &Path,
    run: bool,
) -> Result<TranspileReport> {
    if funcs.is_empty() {
        bail!("no functions to transpile");
    }
    // The program's entry point is the C function `sub_<entry>`; confirm it was
    // recovered before doing any work.
    let entry = prog.entry;
    if !funcs.iter().any(|f| f.entry == entry) {
        bail!(
            "entry function 0x{:x} was not recovered (try without --function)",
            entry
        );
    }
    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;

    // Lower every function and emit one translation unit using the shared machine
    // stack (so both stack- and register-passed arguments cross function calls).
    // The mode flag is read during SSA *and* emission, so it wraps both.
    emit::set_shared_stack(true);
    let irfs: Vec<_> = funcs.iter().map(|f| lower(prog, f)).collect();
    let unit = emit::structured::emit_unit(&irfs);
    emit::set_shared_stack(false);

    // program.c — the transpiled unit, with the HLE declarations in scope.
    let program_c = format!("#include \"aret_hle.h\"\n{}", unit);

    // Memory Layout Mapper: restore data sections at their original VAs so
    // absolute pointers (global strings/tables) resolve at runtime.
    let layout = emit_layout(prog);
    let map_call = if layout.is_some() {
        "    __aret_map_memory();\n"
    } else {
        ""
    };
    // aret_main.c — a native entry that maps memory, sets up the single shared
    // machine stack, then drives the transpiled entry point with the stack-top
    // pointer. Every transpiled function threads this `__esp` through its calls.
    let main_c = format!(
        "#include <stdint.h>\n\n\
         /* One shared machine stack for all transpiled functions (UBT M3). */\n\
         static uint8_t aret_stack[1u << 20];\n\n\
         void __aret_map_memory(void);\n\
         uint64_t sub_{entry:x}(uint64_t __esp, uint64_t a, uint64_t c, uint64_t d);\n\n\
         int main(void) {{\n\
         {map_call}    uint64_t esp = (uint64_t)(uintptr_t)(aret_stack + sizeof(aret_stack) - 16);\n\
         \x20   return (int)sub_{entry:x}(esp, 0, 0, 0);\n\
         }}\n",
    );

    let write = |name: &str, body: &str| -> Result<()> {
        std::fs::write(out_dir.join(name), body)
            .with_context(|| format!("failed to write {}", name))
    };
    write("aret_hle.h", HLE_H)?;
    write("aret_hle.c", HLE_C)?;
    write("program.c", &program_c)?;
    write("aret_main.c", &main_c)?;
    // Always provide __aret_map_memory so aret_main.c links; a no-op when the
    // binary has no addressable data sections.
    let layout_c = layout.unwrap_or_else(|| "void __aret_map_memory(void) {}\n".to_string());
    write("aret_layout.c", &layout_c)?;

    // Compile + link natively. The stack-model C masks pointers to 32 bits, so a
    // 32-bit source must be built as a 32-bit process (-m32); 64-bit as -m64.
    let bits = prog.bitness.bits() as u32;
    let march = if bits == 32 { "-m32" } else { "-m64" };
    let cc = std::env::var("CC").unwrap_or_else(|_| "cc".to_string());
    let binary = out_dir.join("app");

    let output = Command::new(&cc)
        .args([
            march,
            "-no-pie", // load our segments elsewhere; keep the original low VAs free
            "-w",
            "-fno-strict-aliasing",
            "-fno-builtin",
            "-O0",
        ])
        .arg(out_dir.join("program.c"))
        .arg(out_dir.join("aret_hle.c"))
        .arg(out_dir.join("aret_main.c"))
        .arg(out_dir.join("aret_layout.c"))
        .arg("-I")
        .arg(out_dir)
        .arg("-o")
        .arg(&binary)
        .output()
        .with_context(|| format!("failed to run {}", cc))?;

    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        bail!("native recompile failed:\n{}", err.trim());
    }

    let run_output = if run {
        let out = Command::new(&binary)
            .output()
            .with_context(|| format!("failed to run {}", binary.display()))?;
        let mut s = String::from_utf8_lossy(&out.stdout).into_owned();
        if !out.stderr.is_empty() {
            s.push_str(&String::from_utf8_lossy(&out.stderr));
        }
        Some(s)
    } else {
        None
    };

    Ok(TranspileReport {
        out_dir: out_dir.to_path_buf(),
        binary,
        functions: irfs.len(),
        bits,
        run_output,
    })
}
