CREATE TABLE p(id INTEGER PRIMARY KEY, nom TEXT NOT NULL, cat TEXT, prix REAL, qte INT DEFAULT 0, CHECK(prix>=0));
INSERT INTO p(nom,cat,prix,qte) VALUES('A','x',10.5,3),('B','x',20.0,1),('C','y',5.25,7),('D','y',100.0,2),('E','x',NULL,5);
SELECT '01 select-where', id,nom FROM p WHERE prix>10 AND cat='x' ORDER BY id;
SELECT '02 agg', cat,count(*),round(sum(prix),2),round(avg(prix),2),max(qte),total(prix) FROM p GROUP BY cat;
SELECT '03 having', cat FROM p GROUP BY cat HAVING count(*)>2;
SELECT '04 join', a.nom,b.nom FROM p a JOIN p b ON a.cat=b.cat AND a.id<b.id ORDER BY 1,2 LIMIT 3;
SELECT '05 left-join', p.nom, x.c FROM p LEFT JOIN (SELECT cat,count(*) c FROM p GROUP BY cat) x ON p.cat=x.cat ORDER BY id LIMIT 3;
SELECT '06 subquery', nom FROM p WHERE prix=(SELECT max(prix) FROM p);
SELECT '07 cte', n FROM (WITH t(n) AS (SELECT count(*) FROM p) SELECT n*2 n FROM t);
SELECT '08 rec-cte', sum(n) FROM (WITH RECURSIVE c(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM c WHERE n<20) SELECT n FROM c);
SELECT '09 union', v FROM (SELECT 1 v UNION SELECT 2 UNION SELECT 1) ORDER BY v;
SELECT '10 intersect-except', (SELECT count(*) FROM (SELECT 1 UNION SELECT 2 INTERSECT SELECT 2)), (SELECT count(*) FROM (SELECT 1 UNION SELECT 2 EXCEPT SELECT 2));
SELECT '11 window', nom, row_number() OVER w, rank() OVER w, dense_rank() OVER w FROM p WINDOW w AS (ORDER BY prix NULLS LAST) LIMIT 4;
SELECT '12 win-lag', id, lag(prix) OVER (ORDER BY id), lead(prix,1,-1) OVER (ORDER BY id) FROM p ORDER BY id LIMIT 3;
SELECT '13 win-frame', id, round(sum(qte) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING),0) FROM p ORDER BY id;
SELECT '14 win-ntile', id, ntile(2) OVER (ORDER BY id) FROM p ORDER BY id;
SELECT '15 string', upper('aé'),lower('AB'),length('héllo'),substr('abcdef',2,3),replace('a.b.c','.','-'),trim('  x  '),instr('abcd','cd');
SELECT '16 string2', printf('%d|%5.2f|%x|%s',42,3.14159,255,'q'), quote('a''b'), char(72,105), hex('AB'), unicode('Z');
SELECT '17 math', round(sqrt(2),6),round(power(2,10),1),round(exp(1),6),round(log(10),6),round(sin(1),6),round(cos(1),6),round(pi(),6);
SELECT '18 like-glob', 'abc' LIKE 'a%', 'abc' GLOB 'a*', 'ABC' LIKE 'abc', 'a_c' LIKE 'a\_c' ESCAPE '\';
SELECT '19 case-coalesce', CASE WHEN prix>50 THEN 'cher' WHEN prix IS NULL THEN 'na' ELSE 'ok' END, coalesce(prix,-1), ifnull(prix,0), nullif(qte,0) FROM p ORDER BY id LIMIT 3;
SELECT '20 cast-type', cast('42.9' AS INTEGER), cast(42 AS TEXT)||'x', typeof(1),typeof(1.0),typeof('a'),typeof(NULL);
SELECT '21 json', json_extract('{"a":{"b":[10,20,30]}}','$.a.b[1]'), json_array_length('[1,2,3,4]'), json_valid('{bad'), json_object('k',42);
SELECT '22 date', date('2024-01-31','+1 month'), strftime('%Y-%m-%d %H:%M',datetime('2024-06-15 08:30:00','+90 minutes')), cast(julianday('2000-01-01') AS INT);
SELECT '23 group_concat', group_concat(nom ORDER BY id) FROM p WHERE cat='x';
SELECT '24 distinct-filter', count(DISTINCT cat), sum(prix) FILTER (WHERE cat='y') FROM p;
UPDATE p SET qte=qte+1 WHERE cat='x' RETURNING id,qte;
SELECT '26 collate', count(*) FROM p WHERE nom='a' COLLATE NOCASE;
CREATE INDEX ip ON p(prix) WHERE prix IS NOT NULL;
SELECT '27 partial-idx', nom FROM p WHERE prix<10 ORDER BY prix;
CREATE VIEW vv AS SELECT cat, sum(prix) s FROM p GROUP BY cat;
SELECT '28 view', cat, round(s,2) FROM vv ORDER BY cat;
CREATE TABLE gc(a INT, b INT GENERATED ALWAYS AS (a*a) STORED);
INSERT INTO gc(a) VALUES(3),(4);
SELECT '29 gencol', a,b FROM gc ORDER BY a;
CREATE TABLE log(m TEXT);
CREATE TRIGGER tg AFTER INSERT ON gc BEGIN INSERT INTO log VALUES('added '||NEW.a); END;
INSERT INTO gc(a) VALUES(5);
SELECT '30 trigger', m FROM log;
