//! Stack-pop counts for `__stdcall` Win32 imports (the callee-pops-args ABI).
//!
//! A 32-bit `__stdcall` callee removes its own arguments from the stack with
//! `ret N`. The transpiler's import shims read arguments off the modelled stack
//! but never pop them, so without correction `esp` ends `N` bytes too low after
//! every stdcall import call — corrupting later stack-relative accesses (a real
//! BusyBox bug: `SetLastError` left `esp` off by 4, so a spilled `fd` was reloaded
//! from the wrong slot and writes went to fd 0).
//!
//! The pop count is the `@N` decoration mingw's import libraries attach to these
//! symbols (`__imp__SetLastError@4`). That decoration is stripped from the PE
//! import table (only `SetLastError` survives), but `@N` is a fixed property of
//! each Win32 API — identical in every binary — so it is encoded here once. The
//! list covers the kernel32/user32/advapi32/ws2_32 stdcall functions seen in
//! practice; it is purely additive (an unlisted import just gets no pop modelled,
//! the prior behaviour) and reusable across binaries.

/// Bytes a `__stdcall` import pops on return (`@N`), or `None` if unknown/cdecl.
/// `name` is the raw PE import name (any single leading underscore is ignored).
pub fn stdcall_pop_bytes(name: &str) -> Option<u32> {
    let n = name.strip_prefix('_').unwrap_or(name);
    TABLE.binary_search_by(|&(k, _)| k.cmp(n)).ok().map(|i| TABLE[i].1)
}

/// (name, pop-bytes), sorted by name for binary search. `@0` functions are
/// omitted (nothing to pop).
static TABLE: &[(&str, u32)] = &[
    ("AccessCheck", 32),
    ("AddAtomA", 4),
    ("AddAtomW", 4),
    ("AdjustTokenPrivileges", 24),
    ("AdjustWindowRect", 12),
    ("AdjustWindowRectEx", 16),
    ("AllocateAndInitializeSid", 44),
    ("AppendMenuA", 16),
    ("AppendMenuW", 16),
    ("BeginDeferWindowPos", 4),
    ("BeginPaint", 8),
    ("BitBlt", 36),
    ("BringWindowToTop", 4),
    ("CallNextHookEx", 16),
    ("CallWindowProcA", 20),
    ("CallWindowProcW", 20),
    ("CharLowerA", 4),
    ("CharLowerBuffA", 8),
    ("CharLowerBuffW", 8),
    ("CharLowerW", 4),
    ("CharNextA", 4),
    ("CharNextW", 4),
    ("CharPrevA", 8),
    ("CharPrevExA", 16),
    ("CharPrevW", 8),
    ("CharToOemA", 8),
    ("CharToOemBuffA", 12),
    ("CharUpperA", 4),
    ("CharUpperBuffA", 8),
    ("CharUpperBuffW", 8),
    ("CharUpperW", 4),
    ("CheckDlgButton", 12),
    ("CheckMenuItem", 12),
    ("CheckTokenMembership", 12),
    ("ChildWindowFromPoint", 12),
    ("ClientToScreen", 8),
    ("CloseHandle", 4),
    ("ClosePrinter", 4),
    ("CoInitialize", 4),
    ("CoInitializeEx", 8),
    ("CoTaskMemAlloc", 4),
    ("CoTaskMemFree", 4),
    ("CoTaskMemRealloc", 8),
    ("CombineRgn", 16),
    ("CompareFileTime", 8),
    ("CompareStringA", 24),
    ("CompareStringW", 24),
    ("ConvertDefaultLocale", 4),
    ("CopyIcon", 4),
    ("CopyImage", 20),
    ("CopyRect", 8),
    ("CopySid", 12),
    ("CreateBitmap", 20),
    ("CreateCaret", 16),
    ("CreateCompatibleBitmap", 12),
    ("CreateCompatibleDC", 4),
    ("CreateConsoleScreenBuffer", 20),
    ("CreateDIBSection", 24),
    ("CreateDialogIndirectParamA", 20),
    ("CreateDialogIndirectParamW", 20),
    ("CreateDialogParamA", 20),
    ("CreateDialogParamW", 20),
    ("CreateDirectoryA", 8),
    ("CreateDirectoryW", 8),
    ("CreateEventA", 16),
    ("CreateEventW", 16),
    ("CreateFileA", 28),
    ("CreateFileMappingA", 24),
    ("CreateFileMappingW", 24),
    ("CreateFileW", 28),
    ("CreateFontA", 56),
    ("CreateFontIndirectA", 4),
    ("CreateFontIndirectW", 4),
    ("CreateFontW", 56),
    ("CreateIconIndirect", 4),
    ("CreateMutexA", 12),
    ("CreateMutexW", 12),
    ("CreateNamedPipeA", 32),
    ("CreatePalette", 4),
    ("CreatePatternBrush", 4),
    ("CreatePen", 12),
    ("CreatePenIndirect", 4),
    ("CreatePipe", 16),
    ("CreatePolygonRgn", 12),
    ("CreateProcessA", 40),
    ("CreateProcessW", 40),
    ("CreateRectRgn", 16),
    ("CreateRectRgnIndirect", 4),
    ("CreateRemoteThread", 28),
    ("CreateRoundRectRgn", 24),
    ("CreateSemaphoreA", 16),
    ("CreateSemaphoreW", 16),
    ("CreateSolidBrush", 4),
    ("CreateThread", 24),
    ("CreateToolhelp32Snapshot", 8),
    ("CreateWindowExA", 48),
    ("CreateWindowExW", 48),
    ("CryptAcquireContextA", 20),
    ("CryptGenRandom", 12),
    ("CryptReleaseContext", 8),
    ("DPtoLP", 12),
    ("DecodePointer", 4),
    ("DefWindowProcA", 16),
    ("DefWindowProcW", 16),
    ("DeferWindowPos", 32),
    ("DeleteAtom", 4),
    ("DeleteCriticalSection", 4),
    ("DeleteDC", 4),
    ("DeleteFileA", 4),
    ("DeleteFileW", 4),
    ("DeleteMenu", 12),
    ("DeleteObject", 4),
    ("DestroyCursor", 4),
    ("DestroyIcon", 4),
    ("DestroyMenu", 4),
    ("DestroyWindow", 4),
    ("DeviceIoControl", 32),
    ("DialogBoxIndirectParamA", 20),
    ("DialogBoxIndirectParamW", 20),
    ("DialogBoxParamA", 20),
    ("DialogBoxParamW", 20),
    ("DisableThreadLibraryCalls", 4),
    ("DispatchMessageA", 4),
    ("DispatchMessageW", 4),
    ("DosDateTimeToFileTime", 12),
    ("DragDetect", 12),
    ("DrawEdge", 16),
    ("DrawFocusRect", 8),
    ("DrawFrameControl", 16),
    ("DrawIcon", 16),
    ("DrawIconEx", 36),
    ("DrawStateW", 40),
    ("DrawTextA", 20),
    ("DrawTextW", 20),
    ("DuplicateHandle", 28),
    ("DuplicateToken", 12),
    ("EnableMenuItem", 12),
    ("EnableWindow", 8),
    ("EncodePointer", 4),
    ("EndDeferWindowPos", 4),
    ("EndDialog", 8),
    ("EndPaint", 8),
    ("EnterCriticalSection", 4),
    ("EnumChildWindows", 12),
    ("EnumFontFamiliesA", 16),
    ("EnumFontFamiliesExA", 20),
    ("EnumFontFamiliesExW", 20),
    ("EnumFontFamiliesW", 16),
    ("EnumPrintersA", 28),
    ("EnumPrintersW", 28),
    ("EnumResourceLanguagesA", 20),
    ("EnumResourceLanguagesW", 20),
    ("EqualRect", 8),
    ("EqualSid", 8),
    ("ExcludeClipRect", 20),
    ("ExitProcess", 4),
    ("ExitThread", 4),
    ("ExitWindowsEx", 8),
    ("ExpandEnvironmentStringsA", 12),
    ("ExtCreatePen", 20),
    ("ExtCreateRegion", 12),
    ("ExtSelectClipRgn", 12),
    ("ExtTextOutA", 32),
    ("ExtTextOutW", 32),
    ("FileTimeToDosDateTime", 12),
    ("FileTimeToLocalFileTime", 8),
    ("FileTimeToSystemTime", 8),
    ("FillConsoleOutputAttribute", 20),
    ("FillConsoleOutputCharacterA", 20),
    ("FillRect", 12),
    ("FillRgn", 12),
    ("FindAtomA", 4),
    ("FindAtomW", 4),
    ("FindClose", 4),
    ("FindFirstFileA", 8),
    ("FindFirstFileW", 8),
    ("FindFirstVolumeA", 8),
    ("FindFirstVolumeW", 8),
    ("FindNextFileA", 8),
    ("FindNextFileW", 8),
    ("FindNextVolumeA", 12),
    ("FindNextVolumeW", 12),
    ("FindResourceA", 12),
    ("FindResourceW", 12),
    ("FindVolumeClose", 4),
    ("FindWindowA", 8),
    ("FindWindowW", 8),
    ("FlushFileBuffers", 4),
    ("FlushViewOfFile", 8),
    ("FoldStringW", 20),
    ("FormatMessageA", 28),
    ("FormatMessageW", 28),
    ("FrameRect", 12),
    ("FrameRgn", 20),
    ("FreeDDElParam", 8),
    ("FreeEnvironmentStringsA", 4),
    ("FreeEnvironmentStringsW", 4),
    ("FreeLibrary", 4),
    ("FreeResource", 4),
    ("FreeSid", 4),
    ("GdiAlphaBlend", 44),
    ("GdiGetCharDimensions", 12),
    ("GdiGetCodePage", 4),
    ("GenerateConsoleCtrlEvent", 8),
    ("GetAsyncKeyState", 4),
    ("GetAtomNameA", 12),
    ("GetAtomNameW", 12),
    ("GetBkColor", 4),
    ("GetBkMode", 4),
    ("GetCPInfo", 8),
    ("GetCaretPos", 4),
    ("GetCharABCWidthsW", 16),
    ("GetCharWidthA", 16),
    ("GetCharWidthInfo", 8),
    ("GetCharWidthW", 16),
    ("GetClassInfoA", 12),
    ("GetClassInfoExA", 12),
    ("GetClassInfoExW", 12),
    ("GetClassInfoW", 12),
    ("GetClassLongA", 8),
    ("GetClassLongW", 8),
    ("GetClassNameA", 12),
    ("GetClassNameW", 12),
    ("GetClientRect", 8),
    ("GetClipBox", 8),
    ("GetClipRgn", 8),
    ("GetClipboardData", 4),
    ("GetCompressedFileSizeA", 8),
    ("GetConsoleMode", 8),
    ("GetConsoleScreenBufferInfo", 8),
    ("GetConsoleTitleA", 8),
    ("GetCurrentDirectoryA", 8),
    ("GetCurrentDirectoryW", 8),
    ("GetCurrentObject", 8),
    ("GetCurrentPositionEx", 8),
    ("GetCursorPos", 4),
    ("GetDC", 4),
    ("GetDCEx", 12),
    ("GetDIBColorTable", 16),
    ("GetDIBits", 28),
    ("GetDateFormatW", 24),
    ("GetDefaultPrinterA", 8),
    ("GetDefaultPrinterW", 8),
    ("GetDesktopWindow", 0),
    ("GetDeviceCaps", 8),
    ("GetDiskFreeSpaceA", 20),
    ("GetDiskFreeSpaceExA", 16),
    ("GetDiskFreeSpaceExW", 16),
    ("GetDlgCtrlID", 4),
    ("GetDlgItem", 8),
    ("GetDlgItemInt", 16),
    ("GetDlgItemTextA", 16),
    ("GetDlgItemTextW", 16),
    ("GetDoubleClickTime", 0),
    ("GetDpiForWindow", 4),
    ("GetDriveTypeA", 4),
    ("GetDriveTypeW", 4),
    ("GetEnvironmentStrings", 0),
    ("GetEnvironmentStringsA", 0),
    ("GetEnvironmentStringsW", 0),
    ("GetEnvironmentVariableA", 12),
    ("GetEnvironmentVariableW", 12),
    ("GetExitCodeProcess", 8),
    ("GetExitCodeThread", 8),
    ("GetExpandedNameA", 8),
    ("GetFileAttributesA", 4),
    ("GetFileAttributesExA", 12),
    ("GetFileAttributesExW", 12),
    ("GetFileAttributesW", 4),
    ("GetFileInformationByHandle", 8),
    ("GetFileSize", 8),
    ("GetFileSizeEx", 8),
    ("GetFileTime", 16),
    ("GetFileType", 4),
    ("GetFileVersionInfoA", 16),
    ("GetFileVersionInfoSizeA", 8),
    ("GetFullPathNameA", 16),
    ("GetFullPathNameW", 16),
    ("GetIconInfo", 8),
    ("GetKeyNameTextW", 12),
    ("GetKeyState", 4),
    ("GetLastActivePopup", 4),
    ("GetLayout", 4),
    ("GetLengthSid", 4),
    ("GetLocalTime", 4),
    ("GetLocaleInfoW", 16),
    ("GetMapMode", 4),
    ("GetMenu", 4),
    ("GetMenuCheckMarkDimensions", 0),
    ("GetMenuItemCount", 4),
    ("GetMenuItemID", 8),
    ("GetMenuState", 12),
    ("GetMenuStringA", 20),
    ("GetMenuStringW", 20),
    ("GetMessageA", 16),
    ("GetMessageW", 16),
    ("GetModuleFileNameA", 12),
    ("GetModuleFileNameW", 12),
    ("GetModuleHandleA", 4),
    ("GetModuleHandleExW", 12),
    ("GetModuleHandleW", 4),
    ("GetMonitorInfoA", 8),
    ("GetMonitorInfoW", 8),
    ("GetNativeSystemInfo", 4),
    ("GetNearestColor", 8),
    ("GetNearestPaletteIndex", 8),
    ("GetNextDlgGroupItem", 12),
    ("GetNextDlgTabItem", 12),
    ("GetNumberOfConsoleInputEvents", 8),
    ("GetObjectA", 12),
    ("GetObjectType", 4),
    ("GetObjectW", 12),
    ("GetOpenFileNameA", 4),
    ("GetPaletteEntries", 16),
    ("GetParent", 4),
    ("GetPixel", 12),
    ("GetPrivateProfileIntA", 16),
    ("GetPrivateProfileStringA", 24),
    ("GetProcAddress", 8),
    ("GetProcessAffinityMask", 12),
    ("GetProcessId", 4),
    ("GetProcessTimes", 20),
    ("GetProcessVersion", 4),
    ("GetProfileIntA", 12),
    ("GetProfileIntW", 12),
    ("GetProfileStringA", 20),
    ("GetPropA", 8),
    ("GetPropW", 8),
    ("GetRgnBox", 8),
    ("GetSaveFileNameA", 4),
    ("GetScrollInfo", 12),
    ("GetScrollPos", 8),
    ("GetScrollRange", 16),
    ("GetSecurityInfo", 32),
    ("GetShortPathNameA", 12),
    ("GetSidIdentifierAuthority", 4),
    ("GetSidLengthRequired", 4),
    ("GetSidSubAuthority", 8),
    ("GetSidSubAuthorityCount", 4),
    ("GetStartupInfoA", 4),
    ("GetStartupInfoW", 4),
    ("GetStdHandle", 4),
    ("GetStockObject", 4),
    ("GetStringTypeA", 20),
    ("GetStringTypeW", 16),
    ("GetSubMenu", 8),
    ("GetSysColor", 4),
    ("GetSysColorBrush", 4),
    ("GetSystemDirectoryA", 8),
    ("GetSystemDirectoryW", 8),
    ("GetSystemInfo", 4),
    ("GetSystemMenu", 8),
    ("GetSystemMetrics", 4),
    ("GetSystemPaletteEntries", 16),
    ("GetSystemPaletteUse", 4),
    ("GetSystemTime", 4),
    ("GetSystemTimeAsFileTime", 4),
    ("GetTabbedTextExtentA", 20),
    ("GetTabbedTextExtentW", 20),
    ("GetTempFileNameA", 16),
    ("GetTempFileNameW", 16),
    ("GetTempPathA", 8),
    ("GetTempPathW", 8),
    ("GetTextAlign", 4),
    ("GetTextCharsetInfo", 12),
    ("GetTextColor", 4),
    ("GetTextExtentExPointA", 28),
    ("GetTextExtentExPointW", 28),
    ("GetTextExtentPoint32A", 16),
    ("GetTextExtentPoint32W", 16),
    ("GetTextExtentPointA", 16),
    ("GetTextExtentPointW", 16),
    ("GetTextMetricsA", 8),
    ("GetTextMetricsW", 8),
    ("GetThreadPriority", 4),
    ("GetTimeZoneInformation", 4),
    ("GetTokenInformation", 20),
    ("GetTopWindow", 4),
    ("GetUserNameA", 8),
    ("GetUserNameW", 8),
    ("GetVersion", 0),
    ("GetVersionExA", 4),
    ("GetVersionExW", 4),
    ("GetViewportExtEx", 8),
    ("GetViewportOrgEx", 8),
    ("GetVolumeInformationA", 32),
    ("GetVolumeInformationW", 32),
    ("GetVolumeNameForVolumeMountPointA", 12),
    ("GetVolumePathNamesForVolumeNameA", 16),
    ("GetWindow", 8),
    ("GetWindowDC", 4),
    ("GetWindowExtEx", 8),
    ("GetWindowLongA", 8),
    ("GetWindowLongW", 8),
    ("GetWindowOrgEx", 8),
    ("GetWindowRect", 8),
    ("GetWindowRgn", 8),
    ("GetWindowTextA", 12),
    ("GetWindowTextLengthA", 4),
    ("GetWindowTextLengthW", 4),
    ("GetWindowTextW", 12),
    ("GetWindowThreadProcessId", 8),
    ("GetWindowsDirectoryA", 8),
    ("GetWindowsDirectoryW", 8),
    ("GlobalAddAtomA", 4),
    ("GlobalAddAtomW", 4),
    ("GlobalAlloc", 8),
    ("GlobalDeleteAtom", 4),
    ("GlobalFindAtomA", 4),
    ("GlobalFindAtomW", 4),
    ("GlobalFree", 4),
    ("GlobalGetAtomNameA", 12),
    ("GlobalGetAtomNameW", 12),
    ("GlobalHandle", 4),
    ("GlobalLock", 4),
    ("GlobalMemoryStatus", 4),
    ("GlobalReAlloc", 12),
    ("GlobalUnlock", 4),
    ("HeapAlloc", 12),
    ("HeapCreate", 12),
    ("HeapDestroy", 4),
    ("HeapFree", 12),
    ("HeapReAlloc", 16),
    ("HeapSize", 12),
    ("HideCaret", 4),
    ("ImageList_Add", 12),
    ("ImageList_AddMasked", 12),
    ("ImageList_Create", 20),
    ("ImageList_Destroy", 4),
    ("ImageList_Draw", 24),
    ("ImageList_GetBkColor", 4),
    ("ImageList_GetIconSize", 12),
    ("ImageList_GetImageCount", 4),
    ("ImageList_SetBkColor", 8),
    ("ImmGetCompositionStringW", 16),
    ("ImmGetContext", 4),
    ("ImmReleaseContext", 8),
    ("ImmSetCompositionFontW", 8),
    ("ImmSetCompositionWindow", 8),
    ("InflateRect", 12),
    ("InitCommonControlsEx", 4),
    ("InitializeCriticalSection", 4),
    ("InitializeCriticalSectionAndSpinCount", 8),
    ("InitializeCriticalSectionEx", 12),
    ("InitializeSListHead", 4),
    ("InitializeSid", 12),
    ("InsertMenuA", 20),
    ("InterlockedDecrement", 4),
    ("InterlockedIncrement", 4),
    ("InternalGetWindowText", 12),
    ("IntersectClipRect", 20),
    ("IntersectRect", 12),
    ("InvalidateRect", 12),
    ("InvalidateRgn", 12),
    ("InvertRect", 8),
    ("IsBadCodePtr", 4),
    ("IsBadReadPtr", 8),
    ("IsBadStringPtrA", 8),
    ("IsBadStringPtrW", 8),
    ("IsBadWritePtr", 8),
    ("IsChild", 8),
    ("IsClipboardFormatAvailable", 4),
    ("IsDBCSLeadByte", 4),
    ("IsDBCSLeadByteEx", 8),
    ("IsDialogMessageA", 8),
    ("IsDialogMessageW", 8),
    ("IsDlgButtonChecked", 8),
    ("IsIconic", 4),
    ("IsProcessorFeaturePresent", 4),
    ("IsRectEmpty", 4),
    ("IsValidCodePage", 4),
    ("IsValidLocale", 8),
    ("IsValidSid", 4),
    ("IsWindow", 4),
    ("IsWindowEnabled", 4),
    ("IsWindowUnicode", 4),
    ("IsWindowVisible", 4),
    ("IsWow64Process", 8),
    ("KillSystemTimer", 8),
    ("KillTimer", 8),
    ("LCMapStringA", 24),
    ("LCMapStringW", 24),
    ("LPtoDP", 12),
    ("LZClose", 4),
    ("LZCopy", 8),
    ("LZInit", 4),
    ("LZOpenFileA", 12),
    ("LZRead", 12),
    ("LZSeek", 12),
    ("LeaveCriticalSection", 4),
    ("LineTo", 12),
    ("LoadBitmapA", 8),
    ("LoadBitmapW", 8),
    ("LoadCursorA", 8),
    ("LoadCursorW", 8),
    ("LoadIconA", 8),
    ("LoadIconW", 8),
    ("LoadImageA", 24),
    ("LoadImageW", 24),
    ("LoadLibraryA", 4),
    ("LoadLibraryExA", 12),
    ("LoadLibraryExW", 12),
    ("LoadLibraryW", 4),
    ("LoadMenuA", 8),
    ("LoadResource", 8),
    ("LoadStringA", 16),
    ("LoadStringW", 16),
    ("LocalAlloc", 8),
    ("LocalFileTimeToFileTime", 8),
    ("LocalFree", 4),
    ("LocalHandle", 4),
    ("LocalLock", 4),
    ("LocalReAlloc", 12),
    ("LocalSize", 4),
    ("LocalUnlock", 4),
    ("LockFile", 20),
    ("LockFileEx", 24),
    ("LockResource", 4),
    ("LookupPrivilegeValueA", 12),
    ("LookupPrivilegeValueW", 12),
    ("MapDialogRect", 8),
    ("MapViewOfFile", 20),
    ("MapVirtualKeyA", 8),
    ("MapVirtualKeyW", 8),
    ("MapWindowPoints", 16),
    ("MessageBeep", 4),
    ("MessageBoxA", 16),
    ("MessageBoxExA", 20),
    ("MessageBoxExW", 20),
    ("MessageBoxW", 16),
    ("ModifyMenuA", 20),
    ("ModifyMenuW", 20),
    ("MonitorFromPoint", 12),
    ("MonitorFromRect", 8),
    ("MonitorFromWindow", 8),
    ("MoveFileA", 8),
    ("MoveFileExA", 12),
    ("MoveFileW", 8),
    ("MoveToEx", 16),
    ("MoveWindow", 24),
    ("MsgWaitForMultipleObjects", 20),
    ("MsgWaitForMultipleObjectsEx", 20),
    ("MulDiv", 12),
    ("MultiByteToWideChar", 24),
    ("NotifyWinEvent", 16),
    ("OemToCharA", 8),
    ("OemToCharBuffA", 12),
    ("OffsetRect", 12),
    ("OffsetViewportOrgEx", 16),
    ("OffsetWindowOrgEx", 16),
    ("OleInitialize", 4),
    ("OpenClipboard", 4),
    ("OpenEventA", 12),
    ("OpenFile", 12),
    ("OpenFileMappingA", 12),
    ("OpenMutexA", 12),
    ("OpenMutexW", 12),
    ("OpenPrinterA", 12),
    ("OpenPrinterW", 12),
    ("OpenProcess", 12),
    ("OpenProcessToken", 12),
    ("OpenSemaphoreA", 12),
    ("OpenSemaphoreW", 12),
    ("OpenThreadToken", 16),
    ("OutputDebugStringA", 4),
    ("PackDDElParam", 12),
    ("PatBlt", 24),
    ("PathAddBackslashA", 4),
    ("PathAddBackslashW", 4),
    ("PathFindExtensionA", 4),
    ("PathFindExtensionW", 4),
    ("PathFindFileNameA", 4),
    ("PathFindFileNameW", 4),
    ("PathIsRelativeA", 4),
    ("PathIsRelativeW", 4),
    ("PathIsRootA", 4),
    ("PathIsRootW", 4),
    ("PathIsUNCA", 4),
    ("PathIsUNCW", 4),
    ("PathRemoveBackslashA", 4),
    ("PathRemoveBackslashW", 4),
    ("PathRemoveFileSpecA", 4),
    ("PathRemoveFileSpecW", 4),
    ("PathSkipRootA", 4),
    ("PathSkipRootW", 4),
    ("PathStripPathA", 4),
    ("PathStripPathW", 4),
    ("PeekConsoleInputW", 16),
    ("PeekMessageA", 20),
    ("PeekMessageW", 20),
    ("PeekNamedPipe", 24),
    ("PlayEnhMetaFile", 12),
    ("PolyPolyline", 16),
    ("Polygon", 12),
    ("Polyline", 12),
    ("PolylineTo", 12),
    ("PostMessageA", 16),
    ("PostMessageW", 16),
    ("PostQuitMessage", 4),
    ("Process32First", 8),
    ("Process32Next", 8),
    ("PtInRect", 12),
    ("QueryPerformanceCounter", 4),
    ("QueryPerformanceFrequency", 4),
    ("RaiseException", 16),
    ("ReadConsoleInputA", 16),
    ("ReadConsoleInputW", 16),
    ("ReadDirectoryChangesW", 32),
    ("ReadFile", 20),
    ("ReadProcessMemory", 20),
    ("RealizePalette", 4),
    ("RectVisible", 8),
    ("Rectangle", 20),
    ("RedrawWindow", 16),
    ("RegCloseKey", 4),
    ("RegCreateKeyA", 12),
    ("RegCreateKeyExA", 36),
    ("RegCreateKeyExW", 36),
    ("RegCreateKeyW", 12),
    ("RegDeleteKeyA", 8),
    ("RegDeleteKeyW", 8),
    ("RegDeleteValueA", 8),
    ("RegDeleteValueW", 8),
    ("RegEnumKeyA", 16),
    ("RegEnumKeyExA", 32),
    ("RegEnumValueA", 32),
    ("RegFlushKey", 4),
    ("RegOpenKeyA", 12),
    ("RegOpenKeyExA", 20),
    ("RegOpenKeyExW", 20),
    ("RegOpenKeyW", 12),
    ("RegQueryInfoKeyA", 48),
    ("RegQueryValueExA", 24),
    ("RegQueryValueExW", 24),
    ("RegSetValueExA", 24),
    ("RegSetValueExW", 24),
    ("RegisterClassA", 4),
    ("RegisterClassExA", 4),
    ("RegisterClassExW", 4),
    ("RegisterClassW", 4),
    ("RegisterClipboardFormatA", 4),
    ("RegisterClipboardFormatW", 4),
    ("RegisterWindowMessageA", 4),
    ("RegisterWindowMessageW", 4),
    ("ReleaseDC", 8),
    ("ReleaseMutex", 4),
    ("ReleaseSemaphore", 12),
    ("RemoveDirectoryA", 4),
    ("RemoveDirectoryW", 4),
    ("RemoveMenu", 12),
    ("RemovePropA", 8),
    ("RemovePropW", 8),
    ("ResetEvent", 4),
    ("ResizePalette", 8),
    ("ResolveDelayLoadedAPI", 24),
    ("RestoreDC", 8),
    ("ResumeThread", 4),
    ("RtlMoveMemory", 12),
    ("RtlUnwind", 16),
    ("SaferComputeTokenFromLevel", 20),
    ("SaferCreateLevel", 20),
    ("SaveDC", 4),
    ("ScaleViewportExtEx", 24),
    ("ScaleWindowExtEx", 24),
    ("ScreenToClient", 8),
    ("ScriptBreak", 16),
    ("ScriptStringAnalyse", 52),
    ("ScriptStringCPtoX", 16),
    ("ScriptStringFree", 4),
    ("ScriptStringGetLogicalWidths", 8),
    ("ScriptStringOut", 32),
    ("ScriptStringXtoCP", 16),
    ("ScriptString_pSize", 4),
    ("ScriptString_pcOutChars", 4),
    ("ScrollWindow", 20),
    ("ScrollWindowEx", 32),
    ("SearchPathA", 24),
    ("SearchPathW", 24),
    ("SelectClipRgn", 8),
    ("SelectObject", 8),
    ("SelectPalette", 12),
    ("SendDlgItemMessageA", 20),
    ("SendDlgItemMessageW", 20),
    ("SendMessageA", 16),
    ("SendMessageW", 16),
    ("SetActiveWindow", 4),
    ("SetBkColor", 8),
    ("SetBkMode", 8),
    ("SetCapture", 4),
    ("SetCaretPos", 8),
    ("SetClipboardData", 8),
    ("SetConsoleActiveScreenBuffer", 4),
    ("SetConsoleCP", 4),
    ("SetConsoleCtrlHandler", 8),
    ("SetConsoleCursorPosition", 8),
    ("SetConsoleMode", 8),
    ("SetConsoleOutputCP", 4),
    ("SetConsoleScreenBufferSize", 8),
    ("SetConsoleTextAttribute", 8),
    ("SetConsoleTitleA", 4),
    ("SetCurrentDirectoryA", 4),
    ("SetCurrentDirectoryW", 4),
    ("SetCursor", 4),
    ("SetDIBColorTable", 16),
    ("SetDIBits", 28),
    ("SetDlgItemInt", 16),
    ("SetDlgItemTextA", 12),
    ("SetDlgItemTextW", 12),
    ("SetEndOfFile", 4),
    ("SetEnvironmentVariableA", 8),
    ("SetErrorMode", 4),
    ("SetEvent", 4),
    ("SetFileAttributesA", 8),
    ("SetFileAttributesW", 8),
    ("SetFilePointer", 16),
    ("SetFilePointerEx", 20),
    ("SetFileTime", 16),
    ("SetFocus", 4),
    ("SetForegroundWindow", 4),
    ("SetHandleCount", 4),
    ("SetHandleInformation", 12),
    ("SetLastError", 4),
    ("SetMapMode", 8),
    ("SetMenu", 8),
    ("SetMenuItemBitmaps", 20),
    ("SetMessageQueue", 4),
    ("SetPaletteEntries", 16),
    ("SetParent", 8),
    ("SetPixel", 16),
    ("SetPixelV", 16),
    ("SetPolyFillMode", 8),
    ("SetPropA", 12),
    ("SetPropW", 12),
    ("SetRect", 20),
    ("SetRectEmpty", 4),
    ("SetRectRgn", 20),
    ("SetScrollInfo", 16),
    ("SetScrollPos", 16),
    ("SetScrollRange", 20),
    ("SetStdHandle", 8),
    ("SetSystemPaletteUse", 8),
    ("SetSystemTime", 4),
    ("SetSystemTimer", 16),
    ("SetTextAlign", 8),
    ("SetTextColor", 8),
    ("SetThreadLocale", 4),
    ("SetThreadPriority", 8),
    ("SetTimer", 16),
    ("SetTokenInformation", 16),
    ("SetUnhandledExceptionFilter", 4),
    ("SetViewportExtEx", 16),
    ("SetViewportOrgEx", 16),
    ("SetWindowExtEx", 16),
    ("SetWindowLongA", 12),
    ("SetWindowLongW", 12),
    ("SetWindowOrgEx", 16),
    ("SetWindowPos", 28),
    ("SetWindowRgn", 12),
    ("SetWindowTextA", 8),
    ("SetWindowTextW", 8),
    ("SetWindowsHookExA", 16),
    ("SetWindowsHookExW", 16),
    ("ShowCaret", 4),
    ("ShowCursor", 4),
    ("ShowScrollBar", 12),
    ("ShowWindow", 8),
    ("SizeofResource", 8),
    ("Sleep", 4),
    ("SleepEx", 8),
    ("StrCmpIW", 8),
    ("StrCmpNIW", 12),
    ("StretchBlt", 44),
    ("StretchDIBits", 52),
    ("SubtractRect", 12),
    ("SuspendThread", 4),
    ("SysAllocString", 4),
    ("SysAllocStringLen", 8),
    ("SysFreeString", 4),
    ("SysStringByteLen", 4),
    ("SysStringLen", 4),
    ("SystemFunction036", 8),
    ("SystemParametersInfoA", 16),
    ("SystemParametersInfoW", 16),
    ("SystemTimeToFileTime", 8),
    ("TabbedTextOutA", 32),
    ("TabbedTextOutW", 32),
    ("TerminateProcess", 8),
    ("TerminateThread", 8),
    ("TextOutA", 20),
    ("TextOutW", 20),
    ("TlsFree", 4),
    ("TlsGetValue", 4),
    ("TlsSetValue", 8),
    ("TrackMouseEvent", 4),
    ("TrackPopupMenu", 28),
    ("TrackPopupMenuEx", 24),
    ("TranslateMessage", 4),
    ("TryEnterCriticalSection", 4),
    ("UnhandledExceptionFilter", 4),
    ("UnhookWindowsHookEx", 4),
    ("UnionRect", 12),
    ("UnlockFile", 20),
    ("UnlockFileEx", 20),
    ("UnmapViewOfFile", 4),
    ("UnpackDDElParam", 16),
    ("UnrealizeObject", 4),
    ("UnregisterClassA", 8),
    ("UnregisterClassW", 8),
    ("UpdateWindow", 4),
    ("ValidateRect", 8),
    ("ValidateRgn", 8),
    ("VerQueryValueA", 16),
    ("VirtualAlloc", 16),
    ("VirtualFree", 12),
    ("VirtualProtect", 16),
    ("VirtualQuery", 12),
    ("WSAEnumNetworkEvents", 12),
    ("WSAEventSelect", 12),
    ("WSASetLastError", 4),
    ("WSASocketA", 24),
    ("WSAStartup", 8),
    ("WaitForInputIdle", 8),
    ("WaitForMultipleObjects", 16),
    ("WaitForSingleObject", 8),
    ("WideCharToMultiByte", 32),
    ("WinExec", 8),
    ("WinHelpA", 16),
    ("WinHelpW", 16),
    ("WindowFromPoint", 8),
    ("WriteConsoleA", 20),
    ("WriteConsoleW", 20),
    ("WriteFile", 20),
    ("WritePrivateProfileStringA", 16),
    ("accept", 12),
    ("bind", 12),
    ("closesocket", 4),
    ("connect", 12),
    ("freeaddrinfo", 4),
    ("getaddrinfo", 16),
    ("gethostbyaddr", 12),
    ("gethostname", 8),
    ("getnameinfo", 28),
    ("getpeername", 12),
    ("hread", 12),
    ("hwrite", 12),
    ("lclose", 4),
    ("lcreat", 8),
    ("listen", 8),
    ("llseek", 12),
    ("lopen", 8),
    ("lread", 12),
    ("lstrcatA", 8),
    ("lstrcatW", 8),
    ("lstrcmpA", 8),
    ("lstrcmpW", 8),
    ("lstrcmpiA", 8),
    ("lstrcmpiW", 8),
    ("lstrcpyA", 8),
    ("lstrcpyW", 8),
    ("lstrcpynA", 12),
    ("lstrlenA", 4),
    ("lstrlenW", 4),
    ("lwrite", 12),
    ("recv", 16),
    ("select", 20),
    ("setsockopt", 20),
    ("shutdown", 8),
    ("wvsprintfA", 12),
    ("wvsprintfW", 12),
];

/// Win32 imports with a **proven `@0`** decoration (zero arguments → nothing to
/// pop) **whose return value is a SCALAR** (a code page, a count, an id, a error
/// code, a bool). They are deliberately absent from `TABLE` (the product needs no
/// `esp` compensation for them, cf. header), but the funcdiff oracle needs to know
/// they are *known* zero-pop — not merely *unlisted* — so it can stub them
/// **faithfully** (`ret 0`) and thereby score their callers instead of skipping
/// every function that calls `GetLastError`/`GetACP`/… . The `@0` is ground truth
/// (the `__imp__NAME@0` decoration in the i686 mingw import libs); the list is
/// data-driven (imports real binaries call). Oracle-only: never consulted by
/// `build.rs`. Sorted for binary search.
///
/// **Pointer/handle-returning `@0` imports are EXCLUDED** (e.g. `GetCommandLineA`,
/// `GetEnvironmentStrings`, `GetProcessHeap`, `GetConsoleWindow`, `GetCurrentProcess`):
/// a symmetric stub returns `eax = 0`, and when the callee then **dereferences** that
/// pointer, Unicorn (which maps a zeroed page at address 0 for `fs:[disp]`/SEH) walks
/// it while the interpreter has no region there — the two diverge on a NULL-deref that
/// is an artifact of stubbing, not a lift bug (a false-correct/false-positive verdict).
/// Proven: including them made 7za fn `0x447f00` diverge (`stack +0x7fd4`); excluding
/// them restored 0 divergence. A scalar `eax = 0` is used as data by both engines
/// identically, so it is safe. (See the journal 2026-07-17.)
pub fn is_zero_pop_import(name: &str) -> bool {
    let n = name.strip_prefix('_').unwrap_or(name);
    ZERO_POP.binary_search(&n).is_ok()
}

static ZERO_POP: &[&str] = &[
    "AreFileApisANSI",     // BOOL
    "DebugBreak",          // void
    "GetACP",              // UINT (code page)
    "GetConsoleCP",        // UINT
    "GetConsoleOutputCP",  // UINT
    "GetCurrentProcessId", // DWORD
    "GetCurrentThreadId",  // DWORD
    "GetLastError",        // DWORD
    "GetLogicalDrives",    // DWORD (bitmask)
    "GetOEMCP",            // UINT
    "GetTickCount",        // DWORD
    "GetVersion",          // DWORD (packed)
    "SetFileApisToOEM",    // void
    "TlsAlloc",            // DWORD (slot index)
];

#[cfg(test)]
mod tests {
    use super::{TABLE, ZERO_POP};

    /// `ZERO_POP` is binary-searched by `is_zero_pop_import`; keep it sorted.
    #[test]
    fn zero_pop_is_sorted() {
        for pair in ZERO_POP.windows(2) {
            assert!(pair[0] < pair[1], "ZERO_POP not sorted: {:?} !< {:?}", pair[0], pair[1]);
        }
    }

    /// `stdcall_pop_bytes` binary-searches `TABLE`, so an out-of-order entry
    /// silently makes some imports unfindable — their pop is skipped and every
    /// later stack access drifts. Guard the invariant here instead of trusting
    /// hand-maintained alphabetical order.
    #[test]
    fn table_is_sorted_by_name() {
        for pair in TABLE.windows(2) {
            assert!(
                pair[0].0 < pair[1].0,
                "stdcall_pops TABLE not sorted: {:?} !< {:?}",
                pair[0].0,
                pair[1].0
            );
        }
    }
}
