#!/usr/bin/env python3
"""Generate CP437 (OEM) <-> UTF-16 tables, MEASURED from Wine (doc 82, OEM leg).

Mirrors gen_cp1252.py for the OEM code page (GetOEMCP()=437): the ntdll floor's RtlOemToUnicodeN
/ RtlUnicodeToOemN and kernel32 (CP_OEMCP) convert through CP437 with the same best-fit contract
as CP1252. Both tables are measured, never guessed:
  * forward: MultiByteToWideChar(437) over every byte 0x00-0xFF -> a 256-entry byte->UTF16 table;
  * reverse: WideCharToMultiByte(437) over every code point, keeping those that do NOT hit the
    default char '?' (0x3F) -> the exact best-fit table; anything else maps to '?'.
The win_cp437 fixture re-checks both against Wine.

Run (needs wine + mingw): python3 tools/gen_cp437.py  # writes runtime/aret_hle/cp437_tables.h
"""
import os, subprocess, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "runtime/aret_hle/cp437_tables.h")
MINGW = os.environ.get("MINGW_GCC", "i686-w64-mingw32-gcc")

PROG = r'''
#include <windows.h>
#include <stdio.h>
int main(void){
    /* forward: every OEM byte -> UTF16 */
    for(unsigned b=0;b<=0xFF;b++){
        char c=(char)b; unsigned short w=0;
        int n=MultiByteToWideChar(437,0,&c,1,(WCHAR*)&w,1);
        printf("F %u %u\n", b, n==1?w:0x3F);
    }
    /* reverse: every code point -> OEM byte, skip the default-char misses */
    for(unsigned c=1;c<=0xFFFF;c++){
        unsigned short w=(unsigned short)c; char o[4]={0}; BOOL used=0;
        int n=WideCharToMultiByte(437,0,(WCHAR*)&w,1,o,4,NULL,&used);
        if(n==1 && !used) printf("R %u %u\n", c, (unsigned char)o[0]);
    }
    return 0;
}
'''


def main():
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "p.c"); exe = os.path.join(d, "p.exe")
        open(src, "w").write(PROG)
        subprocess.run([MINGW, "-O1", "-w", src, "-o", exe], check=True)
        out = subprocess.run(["wine", exe], capture_output=True, text=True,
                             env=dict(os.environ, WINEDEBUG="-all"), timeout=180).stdout
    fwd = [0x3F] * 256
    rev = []
    for line in out.splitlines():
        t = line.split()
        if t[0] == "F":
            fwd[int(t[1])] = int(t[2])
        elif t[0] == "R":
            rev.append((int(t[1]), int(t[2])))
    rev.sort()
    with open(OUT, "w") as f:
        f.write("/* GENERATED by tools/gen_cp437.py — MEASURED from Wine (CP437/OEM). Forward is a\n"
                " * 256-entry byte->UTF16 table; reverse lists code points that map to a real byte\n"
                " * (best-fit incl.), everything else -> '?' (0x3F). Bit-identical Wine. */\n")
        f.write("static const uint16_t aret_cp437_fwd[256] = {\n")
        for i in range(0, 256, 16):
            f.write("    " + " ".join(f"{v}," for v in fwd[i:i+16]) + "\n")
        f.write("};\n")
        f.write("struct aret_cp437_rev { uint16_t cp; uint8_t b; };\n")
        f.write(f"static const struct aret_cp437_rev aret_cp437_rev_tab[{len(rev)}] = {{\n")
        for i in range(0, len(rev), 8):
            f.write("    " + " ".join(f"{{{cp},{b}}}," for cp, b in rev[i:i+8]) + "\n")
        f.write("};\n")
    print(f"wrote {OUT}: 256 forward, {len(rev)} reverse entries")


if __name__ == "__main__":
    main()
