#!/usr/bin/env python3
"""Generate the CP1252 REVERSE (UTF-16 -> ANSI) table, MEASURED from Wine (doc 82, plan A rev).

Windows' WideCharToMultiByte(CP_ACP) and ntdll's RtlUnicodeToMultiByteN both map a code point to
a CP1252 byte using the exact CP1252 slots PLUS a best-fit table (U+0100 'A-macron' -> 'A',
U+2044 fraction-slash -> '/', ...); only a genuinely unmappable code point becomes '?' (0x3F,
lpUsedDefaultChar=TRUE). Measured identical for kernel32 and ntdll.

Rather than transcribe Wine's best-fit table (guess-prone), we MEASURE it: sweep every code point
0x0001-0xFFFF through Wine's WideCharToMultiByte(CP_ACP) and record those that do NOT hit the
default char. That set (~696 entries) IS Wine's table, bit-identical by construction. Everything
not in it maps to '?'. The winediff fixture (win_cp1252_rev) re-checks it against Wine.

Run (needs wine + mingw): python3 tools/gen_cp1252.py  # writes runtime/aret_hle/cp1252_rev_table.h
"""
import os, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "runtime/aret_hle/cp1252_rev_table.h")
MINGW = os.environ.get("MINGW_GCC", "i686-w64-mingw32-gcc")

SWEEP = r'''
#include <windows.h>
#include <stdio.h>
int main(void){
    for(unsigned c=0;c<=0xFFFF;c++){
        unsigned short w=(unsigned short)c; char b[4]={0}; BOOL used=0;
        int n=WideCharToMultiByte(CP_ACP,0,(WCHAR*)&w,1,b,4,NULL,&used);
        if(n==1 && !used) printf("%u %u\n", c, (unsigned char)b[0]);
    }
    return 0;
}
'''


def main():
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "sweep.c"); exe = os.path.join(d, "sweep.exe")
        open(src, "w").write(SWEEP)
        subprocess.run([MINGW, "-O1", "-w", src, "-o", exe], check=True)
        env = dict(os.environ, WINEDEBUG="-all")
        out = subprocess.run(["wine", exe], capture_output=True, text=True, env=env, timeout=180).stdout
    rows = []
    for line in out.splitlines():
        cp, b = line.split()
        rows.append((int(cp), int(b)))
    rows.sort()
    with open(OUT, "w") as f:
        f.write("/* GENERATED by tools/gen_cp1252.py — MEASURED from Wine's WideCharToMultiByte(CP_ACP).\n"
                " * Code points NOT listed map to the default char '?' (0x3F). Sorted by code point\n"
                " * for binary search. Bit-identical Wine by construction (kernel32 == ntdll). */\n")
        f.write("struct aret_cp1252_rev { uint16_t cp; uint8_t b; };\n")
        f.write(f"static const struct aret_cp1252_rev aret_cp1252_rev_tab[{len(rows)}] = {{\n")
        for i in range(0, len(rows), 8):
            chunk = rows[i:i+8]
            f.write("    " + " ".join(f"{{{cp},{b}}}," for cp, b in chunk) + "\n")
        f.write("};\n")
    print(f"wrote {OUT}: {len(rows)} entries")


if __name__ == "__main__":
    main()
