#!/usr/bin/env python3
"""Extract Wine's code-page table from dlls/mlang/mlang.c into a C table for the ARET HLE.

This is the LIGHT form of "reuse Wine's implementation, compiled in" (doc 81 I12): we do
NOT link Wine and we do NOT transpile Wine's builtin mlang.dll (a relay stub) — we take
Wine's DATA (the code-page descriptions, MIME charset names, fonts, flags), which is the
ground truth, and emit it as a static C table. The resulting binary is fully autonomous.

Source of truth: Wine's mlang.c has, per script family, an array of
    { L"description", codepage, FLAGS, L"web", L"header", L"body"[, L"alias"] }
wrapped by mlang_data[] = { L"Family", family_cp, ARRAY_SIZE(arr), arr, L"fixed", L"prop", sid }.
GetCodePageInfo(cp) fills MIMECPINFO from the matching entry + its family's fonts + a
bGDICharset derived from the family codepage via TranslateCharsetInfo (done at runtime by
the HLE, which already models TranslateCharsetInfo).

Run: python3 tools/gen_mlang_cp.py   # writes runtime/aret_hle/mlang_cp_table.h
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.environ.get("WINE_MLANG_C",
    "/tmp/claude-0/-home-user-Automatic-reverse-engineering-toolkit/"
    "fa3b82aa-c7d3-5f61-b1c4-fe969d2eec4c/scratchpad/wine/mlang.c")
OUT = os.path.join(ROOT, "runtime/aret_hle/mlang_cp_table.h")

# MIMECONTF_* values from mingw's mlang.h (flags are |-joined constants).
FLAGS = {
    "MIMECONTF_MAILNEWS": 0x1, "MIMECONTF_BROWSER": 0x2, "MIMECONTF_MINIMAL": 0x4,
    "MIMECONTF_IMPORT": 0x8, "MIMECONTF_SAVABLE_MAILNEWS": 0x100,
    "MIMECONTF_SAVABLE_BROWSER": 0x200, "MIMECONTF_EXPORT": 0x400,
    "MIMECONTF_PRIVCONVERTER": 0x10000, "MIMECONTF_VALID": 0x20000,
    "MIMECONTF_VALID_NLS": 0x40000, "MIMECONTF_MIME_IE4": 0x10000000,
    "MIMECONTF_MIME_LATEST": 0x20000000, "MIMECONTF_MIME_REGISTRY": 0x40000000,
}

ENTRY = re.compile(
    r'\{\s*L"(?P<desc>[^"]*)"\s*,\s*(?P<cp>\d+)\s*,\s*(?P<flags>[^,]+?)\s*,\s*'
    r'L"(?P<web>[^"]*)"\s*,\s*L"(?P<header>[^"]*)"\s*,\s*L"(?P<body>[^"]*)"', re.S)
ARR = re.compile(r'static const MIME_CP_INFO (\w+)\[\]\s*=\s*\{(.*?)\n\};', re.S)
FAM = re.compile(
    r'\{\s*L"[^"]*"\s*,\s*(?P<famcp>\d+)\s*,\s*ARRAY_SIZE\((?P<arr>\w+)\)\s*,\s*'
    r'\w+\s*,\s*L"(?P<fixed>[^"]*)"\s*,\s*L"(?P<prop>[^"]*)"', re.S)

def resolve_flags(expr):
    v = 0
    for tok in re.findall(r'MIMECONTF_[A-Z_0-9]+', expr):
        v |= FLAGS.get(tok, 0)
    return v

def main():
    if not os.path.isfile(SRC):
        sys.exit(f"Wine mlang.c not found at {SRC} (set WINE_MLANG_C)")
    text = open(SRC).read()
    arrays = {name: body for name, body in ARR.findall(text)}
    fam = {m.group("arr"): (int(m.group("famcp")), m.group("fixed"), m.group("prop"))
           for m in FAM.finditer(text)}
    rows = []
    for arr_name, body in arrays.items():
        if arr_name not in fam:
            continue                                  # unicode_cp etc. not in mlang_data
        famcp, fixed, prop = fam[arr_name]
        for m in ENTRY.finditer(body):
            rows.append((int(m.group("cp")), famcp, resolve_flags(m.group("flags")),
                         m.group("desc"), m.group("web"), m.group("header"),
                         m.group("body"), fixed, prop))
    # De-dup by codepage (a cp appears once); keep first, stable order by cp.
    seen = {}
    for r in rows:
        seen.setdefault(r[0], r)
    rows = [seen[k] for k in sorted(seen)]

    def c(s):  # C string literal (data is ASCII)
        return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

    with open(OUT, "w") as f:
        f.write("/* GENERATED by tools/gen_mlang_cp.py from Wine's dlls/mlang/mlang.c.\n"
                " * Code-page table data (descriptions, MIME charset names, fonts, flags),\n"
                " * extracted from Wine and compiled in; no Wine at runtime. Do not edit. */\n")
        f.write("struct aret_mlang_cp {\n"
                "    uint32_t cp, family_cp, flags;\n"
                "    const char *desc, *web, *header, *body, *fixed, *prop;\n};\n")
        f.write(f"static const struct aret_mlang_cp aret_mlang_cps[] = {{\n")
        for cp, famcp, fl, desc, web, hdr, body, fixed, prop in rows:
            f.write(f"    {{ {cp}, {famcp}, 0x{fl:x}, {c(desc)}, {c(web)}, "
                    f"{c(hdr)}, {c(body)}, {c(fixed)}, {c(prop)} }},\n")
        f.write("};\n")
    print(f"wrote {OUT}: {len(rows)} code pages")

if __name__ == "__main__":
    main()
