//! Experimental LLVM IR backend (rev.ng-style direct IR emission), an
//! alternative to the C backend. Proof of concept: it covers the common
//! integer / memory / branch / call subset — enough to compile real recovered
//! functions through the LLVM toolchain (`llvm-as`/`llc`/`clang`) and get LLVM's
//! optimisation and retargetable codegen for free, instead of going through C.
//!
//! Modelling choices (kept deliberately simple and robust):
//! * every IR value and the frame base is an `i64` held in an `alloca`
//!   (LLVM's `mem2reg`/`-O2` promotes these straight back to SSA registers);
//! * memory accesses go through `inttoptr` (the program models a flat address
//!   space, exactly like the C backend's `*(uintN*)addr`);
//! * anything not yet modelled is emitted as a constant `0` with a `; TODO`
//!   note, so the produced module is always *valid* LLVM IR.

use crate::ir::types::*;
use std::collections::BTreeSet;
use std::fmt::Write;

const MODULE_HEADER: &str = "; Generated by ARET — experimental LLVM IR backend\n\
target datalayout = \"e-m:e-p:32:32-i64:64-f80:32-n8:16:32-S128\"\n\
target triple = \"i386-pc-linux-gnu\"\n\n";

/// Declare an external callee — a `declare` + `define` of the same symbol is a
/// redefinition error, so this is only for symbols not defined in the module.
/// x87 helpers get their precise fp80 types; everything else is a varargs i64
/// function, call-compatible with any argument list we pass.
fn emit_decl(out: &mut String, name: &str) {
    if let Some((ret_fp, arg_fp)) = x87_sig(name) {
        let params: Vec<&str> = arg_fp.iter().map(|&f| llty(f)).collect();
        let _ = writeln!(out, "declare {} @{}({})", llty(ret_fp), name, params.join(", "));
    } else {
        let _ = writeln!(out, "declare i64 @{}(...)", name);
    }
}

/// Emit a complete LLVM IR module for `funcs`.
pub fn emit_unit(funcs: &[IrFunction]) -> String {
    let mut out = String::new();
    out.push_str(MODULE_HEADER);

    let mut callees: BTreeSet<String> = BTreeSet::new();
    let defined: BTreeSet<String> = funcs.iter().map(|f| format!("sub_{:x}", f.entry)).collect();
    for f in funcs {
        collect_call_names(f, &mut callees);
    }
    for name in callees.difference(&defined) {
        emit_decl(&mut out, name);
    }
    if super::shared_stack() {
        out.push_str("declare i64 @aret_call(i32, i64, i64, i64, i64, i64, i64, i64, i64)\n");
    }
    out.push('\n');

    for f in funcs {
        out.push_str(&emit_function(f));
        out.push('\n');
    }
    out
}

/// Emit one self-contained LLVM module per chunk of `chunk_size` functions. A
/// single module for a real binary is gigabytes of textual IR that exhausts
/// `llc`'s memory; chunking bounds per-`llc` cost (compile in parallel, link the
/// objects). Each chunk declares every symbol it might call that it does not
/// itself define (functions defined in another chunk become `declare`s here).
pub fn emit_split(funcs: &[IrFunction], chunk_size: usize) -> Vec<String> {
    let shared = super::shared_stack();
    let all_defined: BTreeSet<String> =
        funcs.iter().map(|f| format!("sub_{:x}", f.entry)).collect();
    let mut callees: BTreeSet<String> = BTreeSet::new();
    for f in funcs {
        collect_call_names(f, &mut callees);
    }
    // Everything that may need a declaration somewhere: external callees plus
    // every defined function (a chunk that calls one defined elsewhere declares it).
    let mut all_names: BTreeSet<String> = callees;
    all_names.extend(all_defined.iter().cloned());

    let mut modules = Vec::new();
    for chunk in funcs.chunks(chunk_size.max(1)) {
        let here: BTreeSet<String> = chunk.iter().map(|f| format!("sub_{:x}", f.entry)).collect();
        let mut out = String::new();
        out.push_str(MODULE_HEADER);
        for name in all_names.difference(&here) {
            emit_decl(&mut out, name);
        }
        if shared {
            out.push_str("declare i64 @aret_call(i32, i64, i64, i64, i64, i64, i64, i64, i64)\n");
        }
        out.push('\n');
        for f in chunk {
            out.push_str(&emit_function(f));
            out.push('\n');
        }
        modules.push(out);
    }
    modules
}

fn collect_call_names(f: &IrFunction, out: &mut BTreeSet<String>) {
    fn ex(e: &Expr, out: &mut BTreeSet<String>) {
        match e {
            Expr::Call { target, args, .. } => {
                match target {
                    CallTarget::Direct(a) => { out.insert(format!("sub_{:x}", a)); }
                    // `asm:` names are unmodelled instructions (the safety valve),
                    // not real functions — never declare them.
                    CallTarget::Named(n) if !n.starts_with("asm:") => { out.insert(n.clone()); }
                    CallTarget::Named(_) => {}
                    CallTarget::Indirect(x) => ex(x, out),
                }
                for a in args { ex(a, out); }
            }
            Expr::Load { addr, .. } => ex(addr, out),
            Expr::Unary(_, x) | Expr::Cast { expr: x, .. } => ex(x, out),
            Expr::Binary(_, a, b) => { ex(a, out); ex(b, out); }
            Expr::Select { cond, then_, else_ } => { ex(cond, out); ex(then_, out); ex(else_, out); }
            _ => {}
        }
    }
    for b in &f.blocks {
        for s in &b.stmts {
            for_each_expr(s, &mut |e| ex(e, out));
        }
    }
}

/// Per-function emission state.
struct Ctx {
    body: String,
    /// next SSA temp id.
    tmp: u32,
    /// allocas already declared (by name), so we declare each once.
    slots: BTreeSet<String>,
    /// alloca-declaration lines (emitted in the entry block).
    decls: String,
    /// SSA value ids that are x87 80-bit values (`x86_fp80`), not `i64`.
    fp80: std::collections::HashSet<u32>,
}

impl Ctx {
    fn fresh(&mut self) -> String {
        let t = format!("%t{}", self.tmp);
        self.tmp += 1;
        t
    }
    /// Ensure an i64 alloca named `%<slot>.addr` exists.
    fn slot(&mut self, name: &str) -> String {
        if self.slots.insert(name.to_string()) {
            let _ = writeln!(self.decls, "  %{}.addr = alloca i64", name);
        }
        format!("%{}.addr", name)
    }
    /// The alloca for SSA value `id` and its LLVM type (`x86_fp80` for x87
    /// values, else `i64`).
    fn vslot(&mut self, id: u32) -> (String, &'static str) {
        let ty = if self.fp80.contains(&id) { "x86_fp80" } else { "i64" };
        let name = format!("v{}", id);
        if self.slots.insert(name.clone()) {
            let _ = writeln!(self.decls, "  %{}.addr = alloca {}", name, ty);
        }
        (format!("%{}.addr", name), ty)
    }
    fn line(&mut self, s: &str) {
        self.body.push_str("  ");
        self.body.push_str(s);
        self.body.push('\n');
    }
}

/// The LLVM signature of an `__x87_*` runtime helper: `(returns_fp80, arg_is_fp80
/// per argument)`. `None` for non-x87 names.
fn x87_sig(name: &str) -> Option<(bool, Vec<bool>)> {
    let n = name.strip_prefix("__x87_")?;
    Some(match n {
        "ld32" | "ld64" | "ld80" | "ild16" | "ild32" | "ild64" => (true, vec![false]),
        "st32" | "st64" | "st80" | "ist16" | "ist32" | "ist64" => (false, vec![false, true]),
        "add" | "sub" | "mul" | "div" | "fmod" => (true, vec![true, true]),
        "abs" | "neg" | "sqrt" | "rint" | "trunc" => (true, vec![true]),
        "one" | "zero" | "retload" => (true, vec![]),
        "lt" | "eq" | "un" => (false, vec![true, true]),
        "retstore" => (false, vec![true]),
        _ => return None,
    })
}

fn llty(fp80: bool) -> &'static str {
    if fp80 { "x86_fp80" } else { "i64" }
}

fn loc_slot_name(loc: &Location) -> String {
    match loc {
        Location::Reg(r) => format!("r{}", r.0),
        Location::Flag(_) => "flag".to_string(),
        Location::Frame(d) => format!("frame_{}", (*d as i64).rem_euclid(1 << 20)),
        Location::Mem => "mem".to_string(),
        Location::Temp(t) => format!("tmp{}", t),
    }
}

fn emit_function(func: &IrFunction) -> String {
    let mut f = func.clone();
    super::destruct_ssa(&mut f);

    let shared = super::shared_stack();

    // Signature. Shared-stack mode: a leading `%esp` parameter plus the volatile
    // register parameters (the caller's stack pointer is threaded through calls);
    // the frame base comes from `%esp`, not a private buffer. Otherwise: register
    // params only, frame base points at a fresh local stack array.
    let mut sig: Vec<String> = Vec::new();
    if shared {
        sig.push("i64 %esp".to_string());
    }
    for v in &f.reg_params {
        sig.push(format!("i64 %v{}", v));
    }
    let mut head = format!("define i64 @sub_{:x}({}) {{\n", f.entry, sig.join(", "));

    let mut cx = Ctx {
        body: String::new(),
        tmp: 0,
        slots: BTreeSet::new(),
        decls: String::new(),
        fp80: f.fp80_values.iter().copied().collect(),
    };

    // Bind register-parameter values to their slots.
    for v in &f.reg_params {
        let (s, _) = cx.vslot(*v);
        cx.line(&format!("store i64 %v{}, ptr {}", v, s));
    }

    // Frame-base values (entry rsp/rbp).
    if shared {
        for v in &f.frame_base_values {
            let (s, _) = cx.vslot(*v);
            cx.line(&format!("store i64 %esp, ptr {}", s));
        }
    } else if !f.frame_base_values.is_empty() {
        cx.line("%frame = alloca [16384 x i8]");
        let base = cx.fresh();
        cx.line(&format!("{} = ptrtoint ptr %frame to i64", base));
        let off = cx.fresh();
        cx.line(&format!("{} = add i64 {}, 14336", off, base));
        for v in &f.frame_base_values {
            let (s, _) = cx.vslot(*v);
            cx.line(&format!("store i64 {}, ptr {}", off, s));
        }
    }

    let entry_id = f
        .blocks
        .iter()
        .find(|b| b.addr == f.entry)
        .map(|b| b.id)
        .unwrap_or(0);
    cx.line(&format!("br label %B{}", entry_id));

    for b in &f.blocks {
        cx.body.push_str(&format!("B{}:\n", b.id));
        let mut terminated = false;
        for s in &b.stmts {
            terminated = emit_stmt(&mut cx, s);
            if terminated {
                break;
            }
        }
        if !terminated {
            // Fallthrough to the next block, or return.
            cx.line("ret i64 0");
        }
    }

    // Assemble: head + alloca decls + body.
    head.push_str(&cx.decls);
    head.push_str(&cx.body);
    head.push_str("}\n");
    head
}

/// Emit a statement. Returns true if it terminated the basic block.
fn emit_stmt(cx: &mut Ctx, s: &Stmt) -> bool {
    match s {
        Stmt::Assign { dst, expr } => {
            let v = emit_expr(cx, expr);
            let (slot, ty) = cx.vslot(dst.0);
            cx.line(&format!("store {} {}, ptr {}", ty, v, slot));
            false
        }
        Stmt::Set { dst, expr } => {
            let v = emit_expr(cx, expr);
            let slot = cx.slot(&loc_slot_name(dst));
            cx.line(&format!("store i64 {}, ptr {}", v, slot));
            false
        }
        Stmt::Store { addr, value, ty } => {
            let a = emit_expr(cx, addr);
            let v = emit_expr(cx, value);
            let bits = int_bits(ty);
            let p = cx.fresh();
            cx.line(&format!("{} = inttoptr i64 {} to ptr", p, a));
            if bits >= 64 {
                cx.line(&format!("store i64 {}, ptr {}", v, p));
            } else {
                let t = cx.fresh();
                cx.line(&format!("{} = trunc i64 {} to i{}", t, v, bits));
                cx.line(&format!("store i{} {}, ptr {}", bits, t, p));
            }
            false
        }
        Stmt::Branch { cond, taken, fallthrough } => {
            let c = emit_expr(cx, cond);
            let b = cx.fresh();
            cx.line(&format!("{} = icmp ne i64 {}, 0", b, c));
            cx.line(&format!("br i1 {}, label %B{}, label %B{}", b, taken.0, fallthrough.0));
            true
        }
        Stmt::Jump(t) => {
            cx.line(&format!("br label %B{}", t.0));
            true
        }
        Stmt::Switch { value, cases, default } => {
            let v = emit_expr(cx, value);
            let mut arms = String::new();
            for (k, b) in cases {
                let _ = write!(arms, " i64 {}, label %B{}", *k as i64, b.0);
            }
            cx.line(&format!("switch i64 {}, label %B{} [{}]", v, default.0, arms));
            true
        }
        Stmt::Return(Some(e)) => {
            let v = emit_expr(cx, e);
            cx.line(&format!("ret i64 {}", v));
            true
        }
        Stmt::Return(None) => {
            cx.line("ret i64 0");
            true
        }
        Stmt::CallStmt(e) => {
            let _ = emit_expr(cx, e);
            false
        }
        Stmt::Asm(t) => {
            cx.line(&format!("; asm (unmodelled): {}", t.replace('\n', " ")));
            false
        }
        Stmt::Nop => false,
    }
}

/// Emit an expression, returning the i64 SSA value (or constant) holding it.
fn emit_expr(cx: &mut Ctx, e: &Expr) -> String {
    match e {
        Expr::Const(c, _) => format!("{}", *c as i64 as i64),
        Expr::Use(v) => {
            let (slot, ty) = cx.vslot(v.0);
            let t = cx.fresh();
            cx.line(&format!("{} = load {}, ptr {}", t, ty, slot));
            t
        }
        Expr::Read(loc) => {
            let slot = cx.slot(&loc_slot_name(loc));
            let t = cx.fresh();
            cx.line(&format!("{} = load i64, ptr {}", t, slot));
            t
        }
        Expr::Load { addr, ty } => {
            let a = emit_expr(cx, addr);
            let bits = int_bits(ty);
            let p = cx.fresh();
            cx.line(&format!("{} = inttoptr i64 {} to ptr", p, a));
            if bits >= 64 {
                let t = cx.fresh();
                cx.line(&format!("{} = load i64, ptr {}", t, p));
                t
            } else {
                let t = cx.fresh();
                cx.line(&format!("{} = load i{}, ptr {}", t, bits, p));
                let z = cx.fresh();
                cx.line(&format!("{} = zext i{} {} to i64", z, bits, t));
                z
            }
        }
        Expr::Binary(op, a, b) => emit_binary(cx, *op, a, b),
        Expr::Unary(op, x) => match op {
            UnOp::Not => { let v = emit_expr(cx, x); let t = cx.fresh(); cx.line(&format!("{} = xor i64 {}, -1", t, v)); t }
            UnOp::Neg => { let v = emit_expr(cx, x); let t = cx.fresh(); cx.line(&format!("{} = sub i64 0, {}", t, v)); t }
            // Sign-extension must actually sign-extend the source width (e.g.
            // `movsx`); zero-extension / truncation are no-ops because the lifter
            // already and-masks sub-word values.
            UnOp::SignExtend => emit_sign_extend(cx, x),
            UnOp::ZeroExtend | UnOp::Truncate => emit_expr(cx, x),
        },
        Expr::Cast { to, expr } => {
            let v = emit_expr(cx, expr);
            let bits = match to {
                Ty::Int { bits, .. } => *bits,
                _ => 64,
            };
            if bits >= 64 {
                v
            } else {
                let signed = matches!(to, Ty::Int { signed: Some(true), .. });
                let tr = cx.fresh();
                cx.line(&format!("{} = trunc i64 {} to i{}", tr, v, bits));
                let r = cx.fresh();
                let ext = if signed { "sext" } else { "zext" };
                cx.line(&format!("{} = {} i{} {} to i64", r, ext, bits, tr));
                r
            }
        }
        Expr::Addr(loc) => {
            // Address of a slot (rare here): not flat-addressable; approximate 0.
            cx.line(&format!("; TODO Addr({})", loc_slot_name(loc)));
            "0".to_string()
        }
        Expr::Call { target, args, .. } => emit_call(cx, target, args),
        Expr::Select { cond, then_, else_ } => {
            let c = emit_expr(cx, cond);
            let t1 = emit_expr(cx, then_);
            let e1 = emit_expr(cx, else_);
            let b = cx.fresh();
            cx.line(&format!("{} = icmp ne i64 {}, 0", b, c));
            let r = cx.fresh();
            cx.line(&format!("{} = select i1 {}, i64 {}, i64 {}", r, b, t1, e1));
            r
        }
        Expr::Phi(_) | Expr::Undef => "0".to_string(),
    }
}

/// Sign-extend an operand to i64, recovering the source width from the value it
/// wraps: an `and`-mask (`x & 0xff/0xffff/0xffffffff`) or a sub-word memory load.
fn emit_sign_extend(cx: &mut Ctx, e: &Expr) -> String {
    // A bare constant carries its width in its type: sign-extend from it (the
    // optimizer folds `const & 0xffffffff` → `const`, dropping the mask the arm
    // below keys on). Without this a 32-bit magic constant with bit 31 set is a
    // large positive i64 in a signed `imul` — same silent miscompile as the C
    // backend (sqlite mingw `h % 23` giving a negative bucket index).
    if let Expr::Const(c, ty) = e {
        let w = int_bits(ty);
        if (1..64).contains(&w) {
            let m = (1u128 << w) - 1;
            let v = (*c as u128) & m;
            let signed: i128 = if (v >> (w - 1)) & 1 == 1 {
                v as i128 - (1i128 << w)
            } else {
                v as i128
            };
            return format!("{}", signed as i64);
        }
    }
    // `x & mask` -> sext from the mask's width.
    if let Expr::Binary(BinOp::And, x, m) = e {
        if let Expr::Const(c, _) = m.as_ref() {
            let w = match *c as u64 {
                0xff => 8,
                0xffff => 16,
                0xffff_ffff => 32,
                _ => 0,
            };
            if w != 0 {
                let v = emit_expr(cx, x);
                let tr = cx.fresh();
                cx.line(&format!("{} = trunc i64 {} to i{}", tr, v, w));
                let r = cx.fresh();
                cx.line(&format!("{} = sext i{} {} to i64", r, w, tr));
                return r;
            }
        }
    }
    // Sub-word load -> load at width, then sign-extend.
    if let Expr::Load { addr, ty } = e {
        let bits = int_bits(ty);
        if bits < 64 {
            let a = emit_expr(cx, addr);
            let p = cx.fresh();
            cx.line(&format!("{} = inttoptr i64 {} to ptr", p, a));
            let t = cx.fresh();
            cx.line(&format!("{} = load i{}, ptr {}", t, bits, p));
            let r = cx.fresh();
            cx.line(&format!("{} = sext i{} {} to i64", r, bits, t));
            return r;
        }
    }
    emit_expr(cx, e)
}

fn emit_binary(cx: &mut Ctx, op: BinOp, a: &Expr, b: &Expr) -> String {
    let x = emit_expr(cx, a);
    let y = emit_expr(cx, b);
    let t = cx.fresh();
    let arith = |t: &str, ins: &str| format!("{} = {} i64 {}, {}", t, ins, x, y);
    // Relational ops produce i1 -> zext to i64.
    let cmp = |cx: &mut Ctx, pred: &str| -> String {
        let c = cx.fresh();
        cx.line(&format!("{} = icmp {} i64 {}, {}", c, pred, x, y));
        let z = cx.fresh();
        cx.line(&format!("{} = zext i1 {} to i64", z, c));
        z
    };
    match op {
        BinOp::Add => { cx.line(&arith(&t, "add")); t }
        BinOp::Sub => { cx.line(&arith(&t, "sub")); t }
        BinOp::Mul => { cx.line(&arith(&t, "mul")); t }
        BinOp::UDiv => { cx.line(&arith(&t, "udiv")); t }
        BinOp::SDiv => { cx.line(&arith(&t, "sdiv")); t }
        BinOp::UMod => { cx.line(&arith(&t, "urem")); t }
        BinOp::SMod => { cx.line(&arith(&t, "srem")); t }
        BinOp::And => { cx.line(&arith(&t, "and")); t }
        BinOp::Or => { cx.line(&arith(&t, "or")); t }
        BinOp::Xor => { cx.line(&arith(&t, "xor")); t }
        BinOp::Shl => { cx.line(&arith(&t, "shl")); t }
        BinOp::Shr => { cx.line(&arith(&t, "lshr")); t }
        BinOp::Sar => { cx.line(&arith(&t, "ashr")); t }
        BinOp::Eq => cmp(cx, "eq"),
        BinOp::Ne => cmp(cx, "ne"),
        BinOp::Ult => cmp(cx, "ult"),
        BinOp::Ule => cmp(cx, "ule"),
        BinOp::Ugt => cmp(cx, "ugt"),
        BinOp::Uge => cmp(cx, "uge"),
        BinOp::Slt => cmp(cx, "slt"),
        BinOp::Sle => cmp(cx, "sle"),
        BinOp::Sgt => cmp(cx, "sgt"),
        BinOp::Sge => cmp(cx, "sge"),
    }
}

fn emit_call(cx: &mut Ctx, target: &CallTarget, args: &[Expr]) -> String {
    // Unmodelled instruction kept as `asm:` — no real call; honest placeholder.
    if let CallTarget::Named(n) = target {
        if n.starts_with("asm:") {
            cx.line(&format!("; asm (unmodelled): {}", n.trim_start_matches("asm:")));
            return "0".to_string();
        }
        // x87 helper: typed `x86_fp80`/`i64` arguments and result.
        if let Some((ret_fp, arg_fp)) = x87_sig(n) {
            let argv: Vec<String> = args
                .iter()
                .enumerate()
                .map(|(i, e)| {
                    let v = emit_expr(cx, e);
                    format!("{} {}", llty(arg_fp.get(i).copied().unwrap_or(false)), v)
                })
                .collect();
            let t = cx.fresh();
            cx.line(&format!("{} = call {} @{}({})", t, llty(ret_fp), n, argv.join(", ")));
            return t;
        }
    }
    // Shared-stack indirect call: a function pointer holds the original code VA,
    // so dispatch through `aret_call(va, esp, eax, ecx, edx, ebp, esi, edi, ebx)`.
    if super::shared_stack() {
        if let CallTarget::Indirect(x) = target {
            let v = emit_expr(cx, x);
            let va = cx.fresh();
            cx.line(&format!("{} = trunc i64 {} to i32", va, v));
            let mut a: Vec<String> = args.iter().map(|e| emit_expr(cx, e)).collect();
            while a.len() < 8 {
                a.push("0".to_string());
            }
            let t = cx.fresh();
            cx.line(&format!(
                "{} = call i64 @aret_call(i32 {}, i64 {}, i64 {}, i64 {}, i64 {}, i64 {}, i64 {}, i64 {}, i64 {})",
                t, va, a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7]
            ));
            return t;
        }
    }

    let argv: Vec<String> = args.iter().map(|a| format!("i64 {}", emit_expr(cx, a))).collect();
    let callee = match target {
        CallTarget::Direct(a) => format!("@sub_{:x}", a),
        CallTarget::Named(n) => format!("@{}", n),
        CallTarget::Indirect(x) => {
            // Call through a computed pointer (non-shared mode).
            let v = emit_expr(cx, x);
            let p = cx.fresh();
            cx.line(&format!("{} = inttoptr i64 {} to ptr", p, v));
            p
        }
    };
    let t = cx.fresh();
    cx.line(&format!("{} = call i64 ({}) {}({})", t, "...", callee, argv.join(", ")));
    t
}

/// Apply `f` to each top-level expression in a statement.
fn for_each_expr(s: &Stmt, f: &mut impl FnMut(&Expr)) {
    match s {
        Stmt::Set { expr, .. } | Stmt::Assign { expr, .. } | Stmt::CallStmt(expr) => f(expr),
        Stmt::Store { addr, value, .. } => { f(addr); f(value); }
        Stmt::Branch { cond, .. } => f(cond),
        Stmt::Switch { value, .. } => f(value),
        Stmt::Return(Some(e)) => f(e),
        _ => {}
    }
}

fn int_bits(t: &Ty) -> u8 {
    super::int_bits(t)
}
